# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nu_eda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eda1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_usageid', models.IntegerField(blank=True, db_column='\ufeffusageid', null=True)),
                ('usetime', models.DateTimeField(blank=True, null=True)),
                ('accesscode', models.IntegerField(blank=True, null=True)),
                ('visualid', models.FloatField(blank=True, null=True)),
                ('rideid', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('useno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eda_1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eda2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usageid', models.IntegerField(blank=True, null=True)),
                ('usetime', models.DateTimeField(blank=True, null=True)),
                ('accesscode', models.IntegerField(blank=True, null=True)),
                ('visualid', models.BigIntegerField(blank=True, null=True)),
                ('rideid', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('useno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'eda_2',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Markov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_ride', models.TextField(blank=True, null=True)),
                ('next_ride', models.TextField(blank=True, null=True)),
                ('dt', models.DateField(blank=True, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('count_u1_visualid_field', models.BigIntegerField(db_column='count(U1.visualid)')),
            ],
            options={
                'db_table': 'markov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MasterUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usgeid', models.FloatField(blank=True, null=True)),
                ('usetime', models.DateTimeField(blank=True, null=True)),
                ('accesscode', models.FloatField(blank=True, null=True)),
                ('visualid', models.FloatField(blank=True, null=True)),
                ('rideid', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('useno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'master_usage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NuEdaChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'nu_eda_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NuEdaQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'nu_eda_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ridestable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_rideid', models.IntegerField(blank=True, db_column='\ufeffRideID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('points', models.IntegerField(blank=True, db_column='Points', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('longname', models.TextField(blank=True, db_column='LongName', null=True)),
            ],
            options={
                'db_table': 'ridestable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sunburst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=20, null=True)),
                ('ride', models.CharField(blank=True, db_column='Ride', max_length=20, null=True)),
                ('hr', models.IntegerField(blank=True, null=True)),
                ('cust_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sunburst',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticketcategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_accesscodeid', models.IntegerField(blank=True, db_column='\ufeffAccessCodeID', null=True)),
                ('accesscode', models.IntegerField(blank=True, db_column='AccessCode', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('type', models.TextField(blank=True, db_column='Type', null=True)),
                ('category', models.TextField(blank=True, db_column='Category', null=True)),
                ('subcategory', models.TextField(blank=True, db_column='Subcategory', null=True)),
            ],
            options={
                'db_table': 'ticketcategories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_usageid', models.IntegerField(blank=True, db_column='\ufeffusageid', null=True)),
                ('usetime', models.TextField(blank=True, null=True)),
                ('accesscode', models.IntegerField(blank=True, null=True)),
                ('visualid', models.BigIntegerField(blank=True, null=True)),
                ('rideid', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('useno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usage',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
